name: law_app
description: Монгол Улсын Үндсэн хууль.
version: 1.0.0+1
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  expandable: ^4.0.0
  flutter_share: ^2.0.0
  flutter_pagewise: ^2.0.4
  shared_preferences: ^2.0.18
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  # network_to_file_image: ^4.0.1
  path_provider: ^2.0.13
  app_version_update: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_large.jpg"

flutter:
  uses-material-design: true
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/SegoeUILight.ttf
    - family: Fregat
      fonts:
        - asset: assets/fonts/Fregat_Mon.ttf
        - asset: assets/fonts/Fregat_Italic_Mon.ttf
          style: italic
        - asset: assets/fonts/Fregat_Bold_Mon.ttf
          weight: 700
        - asset: assets/fonts/Fregat_Bold_Italic_Mon.ttf
          style: italic
          weight: 700
  assets:
    - assets/images/
